insert into public.products (
  slug,
  name,
  category,
  description,
  price,
  image_url,
  is_active,
  sort_order,
  weight
)
values
  ('rokki', 'Рокки', 'Бургеры', 'Пшеничная булочка, соус чесночный и сырный, сочная котлета из говядины, сыр чеддер, сырные палочки моцарелла, салат, помидор, красный лук.', 450, '/assets/products/placeholder-burger.svg', true, 1, '1 шт.'),
  ('sebastian', 'Себастиан', 'Бургеры', 'Пшеничная булочка, соус цезарь, салат, помидор, красный лук, королевские креветки.', 430, '/assets/products/placeholder-burger.svg', true, 2, '1 шт.'),
  ('kantrigrand', 'Бургер КантриГранд сочная котлета из говядины', 'Бургеры', 'Пшеничная булочка, соус барбекю и кетчуп, сочная говяжья котлета, сыр чеддер, свежий салат, помидор и маринованный огурец.', 390, '/assets/products/placeholder-burger.svg', true, 3, '1 шт.'),
  ('borak-abama', 'Борак Абама', 'Бургеры', 'Черная булочка, фирменный соус барбекю, лист салата, свежий помидор, маринованный огурец, красный лук, сочная котлета из говядины, сыр чеддер.', 430, '/assets/products/placeholder-burger.svg', true, 4, '1 шт.'),
  ('voin-drakona', 'Бургер Воин Дракона с сочной говядиной', 'Бургеры', 'Пшеничная булочка, соус фирменный чесночный, салат, лук фри, свежий помидор, сочная котлета из говядины, сыр чеддер.', 390, '/assets/products/placeholder-burger.svg', true, 5, '1 шт.'),
  ('kantribif', 'Бургер КантриБиф с котлетой из говядины', 'Бургеры', 'Пшеничная булочка, соус медовая-горчица и кетчуп, салат, помидор, маринованный огурец, красный лук, сочная котлета из говядины, сыр чеддер.', 390, '/assets/products/placeholder-burger.svg', true, 6, '1 шт.'),
  ('tayson', 'Бургер Тайсон с сочной котлетой из говядины и жареным беконом', 'Бургеры', 'Пшеничная булочка, фирменный соус тейсти, сочная котлета из говядины, помидор, маринованный огурец, салат, жареный бекон, сыр чеддер.', 430, '/assets/products/placeholder-burger.svg', true, 7, '1 шт.'),
  ('firmennaya-shaurma', 'Фирменная Шаурма', 'Шаурма', 'Лаваш тандырный, фирменный соус барбекю, сочная курочка, картошка фри, бекон жареный, маринованный огурец, красный лук, свежий помидор, сырные палочки.', 550, '/assets/products/placeholder-shaurma.svg', true, 8, '1 шт.'),
  ('shaurma-v-lepeshke-govyadina', 'Шаурма в лепешке с запеченной говядиной', 'Шаурма', 'Тандырная лепешка, фирменный чесночный соус, говядина запеченная, свежие овощи: капуста, помидор, огурец, красный лук.', 460, '/assets/products/placeholder-shaurma.svg', true, 9, '1 ед.'),
  ('shaurma-v-lepeshke-svinina', 'Шаурма в лепешке с запеченной свининой', 'Шаурма', 'Тандырная лепешка, соус фирменный чесночный, свинина запеченная, свежие овощи: капуста, помидор, огурец, красный лук.', 390, '/assets/products/placeholder-shaurma.svg', true, 10, '1 ед.'),
  ('shaurma-v-lepeshke-kuritsa', 'Шаурма в лепешке с сочной курочкой', 'Шаурма', 'Тандырная лепешка, фирменный чесночный соус, сочная курочка, свежие овощи: капуста, помидор, огурец, красный лук.', 290, '/assets/products/placeholder-shaurma.svg', true, 11, '1 ед.'),
  ('shaurma-krevetka', 'Шаурма с Королевской креветкой в панировке', 'Шаурма', 'Тандырный лаваш, соус Цезарь, королевские креветки, свежие овощи: капуста, помидор, красный лук.', 410, '/assets/products/placeholder-shaurma.svg', true, 12, '300 г.'),
  ('shaurma-zapechennaya-govyadina', 'Шаурма с запеченной говядиной', 'Шаурма', 'Лаваш тандырный, соус фирменный чесночный, говядина запеченная, свежие овощи: капуста, помидор, огурец, красный лук.', 410, '/assets/products/placeholder-shaurma.svg', true, 13, '370 г.'),
  ('shaurma-zapechennaya-svinina', 'Шаурма с запеченной свининой', 'Шаурма', 'Лаваш тандырный, соус фирменный чесночный, свинина запеченная, свежие овощи: капуста, помидор, огурец, красный лук.', 350, '/assets/products/placeholder-shaurma.svg', true, 14, '370 г.'),
  ('shaurma-kurinaya', 'Шаурма куриная', 'Шаурма', 'Лаваш тандырный, соус фирменный чесночный, сочная курочка, свежие овощи: капуста, помидор, огурец, красный лук.', 240, '/assets/products/placeholder-shaurma.svg', true, 15, '1 шт.'),
  ('hot-dog-barbekyu', 'Хот-Дог Барбекю', 'Хот-Доги', 'Пшеничная булочка, колбаска из свинины, свежие овощи: лист салата, помидор, маринованный огурец, фирменный соус барбекю, лук фри.', 260, '/assets/products/placeholder-hotdog.svg', true, 16, '1 шт.'),
  ('hot-dog-itali', 'Хот-Дог Итали', 'Хот-Доги', 'Пшеничная булочка, колбаска из свинины, лист салата, сыр чеддер, сырный соус, лук фри.', 280, '/assets/products/placeholder-hotdog.svg', true, 17, '1 шт.'),
  ('hot-dog-datskiy', 'Хот-Дог Датский', 'Хот-Доги', 'Пшеничная булочка, колбаска из свинины, лист салата, маринованный огурец, соусы: кетчуп, медово-горчичный, лук фри.', 250, '/assets/products/placeholder-hotdog.svg', true, 18, '1 шт.'),
  ('aydahobox', 'АйдахоБокс', 'Боксы', 'Картофель по-деревенски, сочная курочка, жареный бекон, лук фри, сырный соус.', 310, '/assets/products/placeholder-box.svg', true, 19, '1 шт.'),
  ('boxfood', 'БоксФуд', 'Боксы', 'Картофель фри, сочная курочка, маринованный огурец, лук фри, фирменный чесночный соус.', 300, '/assets/products/placeholder-box.svg', true, 20, '1 шт.'),
  ('krevetki-v-panirovke', 'Креветки в панировке (королевские)', 'Горячие закуски', 'Королевские креветки в панировке — снек для компании.', 390, '/assets/products/placeholder-snack.svg', true, 21, '6/12 шт.'),
  ('naggetsy', 'Наггетсы', 'Горячие закуски', 'Хрустящие кусочки нежного филе в золотистой панировке.', 210, '/assets/products/placeholder-snack.svg', true, 22, '6/12 ед.'),
  ('syrnye-palochki', 'Сырные палочки', 'Горячие закуски', 'Сырные палочки из моцареллы.', 590, '/assets/products/placeholder-snack.svg', true, 23, '12/6 шт.'),
  ('kartofel-po-derevenski', 'Картофель по деревенски', 'Горячие закуски', 'Хрустящий картофель с мягкой сердцевиной.', 260, '/assets/products/placeholder-snack.svg', true, 24, '150/200 г.'),
  ('kartoshka-fri', 'Картошка фри', 'Горячие закуски', 'Хрустящий картофель фри.', 210, '/assets/products/placeholder-snack.svg', true, 25, '150/200 г.'),
  ('krylyshki-barbekyu', 'Крылышки куриные Барбекю', 'Горячие закуски', 'Куриные крылья с фирменным соусом барбекю.', 650, '/assets/products/placeholder-snack.svg', true, 26, '16/8 шт.'),
  ('dobryy-apelsin-1l', 'Добрый Апельсин 1 л', 'Напитки', 'Апельсин.', 140, '/assets/products/placeholder-drink.svg', true, 27, '1 л.'),
  ('dobryy-kola-1l', 'Добрый Кола 1 л', 'Напитки', 'Кола.', 140, '/assets/products/placeholder-drink.svg', true, 28, '1 л.'),
  ('dobryy-kola-zero-1l', 'Добрый Кола 1 л без сахара', 'Напитки', 'Кола без сахара.', 140, '/assets/products/placeholder-drink.svg', true, 29, '1 л.'),
  ('dobryy-kola-zero-05', 'Добрый Кола 0,5 без сахара', 'Напитки', 'Кола без сахара.', 100, '/assets/products/placeholder-drink.svg', true, 30, '500 мл.'),
  ('dobryy-kola-05', 'Добрый Кола 0,5', 'Напитки', 'Кола.', 100, '/assets/products/placeholder-drink.svg', true, 31, '500 мл.'),
  ('dobryy-apelsin-05', 'Добрый Апельсин 0,5', 'Напитки', 'Апельсин.', 100, '/assets/products/placeholder-drink.svg', true, 32, '500 мл.'),
  ('dobryy-apelsin-can-033', 'Добрый Апельсин жб 0,33л', 'Напитки', 'Апельсин.', 90, '/assets/products/placeholder-drink.svg', true, 33, '300 мл.'),
  ('dobryy-kola-zero-can-033', 'Добрый Кола жб 0,33л (без сахара)', 'Напитки', 'Кола без сахара.', 90, '/assets/products/placeholder-drink.svg', true, 34, '300 мл.')
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  image_url = excluded.image_url,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  weight = excluded.weight,
  updated_at = now();
