insert into public.vacancies (
  title,
  slug,
  department,
  employment_type,
  salary_from,
  salary_to,
  salary_unit,
  location,
  schedule,
  description,
  requirements,
  responsibilities,
  benefits,
  is_active,
  sort_order
) values
(
  'Повар',
  'cook',
  'Кухня',
  'Сменный график',
  450,
  null,
  'hour',
  'Точка KARIMOFF',
  'Гибкий график',
  'Готовить фирменные позиции KARIMOFF по стандартам и поддерживать порядок на рабочем месте.',
  'Ответственность, аккуратность, готовность соблюдать стандарты кухни.',
  'Готовить блюда по технологическим картам, следить за чистотой рабочей зоны, помогать команде в час пик.',
  'Оплата от 450 рублей в час на стартовом этапе, обучение, поддержка команды, стабильные выплаты.',
  true,
  10
),
(
  'Администратор',
  'administrator',
  'Сервис',
  'Полная занятость',
  null,
  null,
  'month',
  'Точка KARIMOFF',
  'По договорённости',
  'Помогать команде держать темп, качество сервиса и порядок в операционных процессах.',
  'Опыт в сервисе будет преимуществом, важны спокойствие, внимательность и умение работать с командой.',
  'Координировать смену, контролировать стандарты, общаться с гостями и поддерживать операционный порядок.',
  'Обучение стандартам, понятная зона ответственности, возможность роста внутри команды.',
  true,
  20
),
(
  'Курьер',
  'courier',
  'Доставка',
  'Подработка / смены',
  null,
  null,
  'shift',
  'Город присутствия',
  'Гибкий график',
  'Аккуратно доставлять заказы гостям и помогать сохранять впечатление от бренда после кухни.',
  'Пунктуальность, аккуратность, вежливое общение с гостями.',
  'Получать заказы, доставлять их в согласованное время, бережно обращаться с упаковкой.',
  'Гибкие смены, понятные процессы и поддержка команды.',
  true,
  30
)
on conflict (slug) do update set
  title = excluded.title,
  department = excluded.department,
  employment_type = excluded.employment_type,
  salary_from = excluded.salary_from,
  salary_to = excluded.salary_to,
  salary_unit = excluded.salary_unit,
  location = excluded.location,
  schedule = excluded.schedule,
  description = excluded.description,
  requirements = excluded.requirements,
  responsibilities = excluded.responsibilities,
  benefits = excluded.benefits,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now();
